### ISSUE TITLE
05.06.2021 - 12.06.2021 tarixindəki taskların nəticəsi:

### ISSUE THREAD

**Issue by yasin-mehdiyev** [jalamirzayeva/PragmatechFrontEndProject#1]
Çatışmazlıqlar:

 1) Githuba push edərkən taska aydın şəkildə comment yaz.Git Commentlər yaxşı deyil(Görülən işlər barədə xırda bir comment
     yazsan daha məsləhətlidir.)
 2) Variable adlarınının hamısını ingilis dilində camelCase şəklində yazsan daha məsləhətlidi. Example: let isNumber şəklində
 3) 5-ci taskında alqoritm tam düzgün yazılmayıb o tapşırığa yenidən nəzər yetir.Alqoritmi fərqli input datalarla test etsən bir iki 
     səhv olduğunu görəcəksən
 4) 7-ci taskında underfined bugı var sonuncu element underfined çıxarır

**Comment by jalamirzayeva** [comment]
1. Okay diqqet edecem bundan sonra commentlere.
2. Düzəliş edildi
3. 3 və 4 cü catışmazlığa da deye bilərəmki, hemin 2 taskın buglarını müəllimə bildirdim, sabah dəsrdə birlikdə müzakirə etməyi məsləhət gördü.
